name: Builder

on:
  workflow_dispatch:

jobs:
  build-job:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: src

      - name: Install Python packages
        run: pip install py7zr pefile colorama

      - name: Prepare directory
        working-directory: ./src/bin/installer
        run: python generate-sections.py -f ${{ github.workspace }}/src/toolkit -o ${{ github.workspace }}/src/bin/installer/full

      - name: Prepare documents
        working-directory: ./src/bin/installer
        run: ./build-docs.bat

      - name: Build installer
        working-directory: ./src/bin/installer/full
        run: ISCC.exe setup.iss /DMySrcDir="${{ github.workspace }}/src" /DMyOutputDir="${{ github.workspace }}"

      - name: Upload Setup as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: setup-installer-artifact
          path: ./*.exe
