name: Test Updater
on:
  on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  test-updater:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
     
      - name: Force update all tools
        working-directory: ./bin/updater
        run: ./updater.exe --disable-self-update --disable-progress-bar --disable-install-check --disable-repack --force
